version: '3.7'

services:
  web:
    image: nginx
    labels:
      - "traefik.http.routers.blw.rule=Host(`dev.local.blw.sh`)"
    volumes:
      - .:/usr/share/nginx/html:ro
networks:
  default:
    external:
      name: traefik
