version: '3.7'
services:
  web:
    image: nginx
    # image: pagespeed/nginx-pagespeed
    volumes:
      - .:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=dev.local.blw.sh
      - CERT_NAME=local.blw.sh
networks:
  default:
    external:
      name: proxy-network
